spring.application.name=skilltrack

server.port=${SPRING_DATASOURCE_PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/skilltrack_local}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=3Aol+PPL7CYUiQe2aoseqw/QdpHFQbqKFrTGFcEIQlSZ4/jFLCQR5/0BKebhFsyIJyYwdmlDGcMY8ZvE6lgMAA==
jwt.expiry=43200000
